import type { Source } from '../types/source.js';
import type { Feature } from '../types/feature.js';
import type { FunctionUnit, FunctionUnitMetadata } from '../types/function-unit.js';
import type { KnowledgeIndex } from '../types/index-schema.js';

function formatLineRange(metadata: FunctionUnitMetadata): string {
  const { lineStart, lineEnd } = metadata;
  if (lineStart && lineEnd) return `${lineStart}-${lineEnd}`;
  if (lineStart) return `${lineStart}`;
  return '-';
}

export function renderHeader(source: Source): string {
  const { url, type, lastIndexedAt, version, tags } = source.metadata;
  const indexedDate = lastIndexedAt.split('T')[0];
  const summaryLineParts = [`**Type**: ${type}`, `**Last Indexed**: ${indexedDate}`];
  if (version) summaryLineParts.push(`**Version**: ${version}`);

  const lines = [
    `# Knowledge Index: ${source.name}`,
    ``,
    `> ${source.summary}`,
    ``,
    `**Source**: ${url}  `,
    summaryLineParts.join(' | '),
  ];

  if (tags && tags.length > 0) {
    lines.push(`**Tags**: ${tags.join(', ')}`);
  }

  lines.push('', '---', '');
  return lines.join('\n');
}

export function renderFeatureSection(
  feature: Feature,
  units: readonly FunctionUnit[],
): string {
  const lines = [
    `### ${feature.name}`,
    ``,
    `> ${feature.summary}`,
    ``,
  ];

  if (feature.metadata.path) {
    lines.push(`**Path**: \`${feature.metadata.path}\``, '');
  }

  if (units.length > 0) {
    lines.push(
      '| Function | Description | File | Line |',
      '|----------|-------------|------|------|',
    );

    for (const unit of units) {
      const file = unit.metadata.filePath
        ? `\`${unit.metadata.filePath}\``
        : '-';
      const line = formatLineRange(unit.metadata);
      lines.push(
        `| \`${unit.name}\` | ${unit.description} | ${file} | ${line} |`,
      );
    }
  }

  lines.push('');
  return lines.join('\n');
}

export function renderFooter(index: KnowledgeIndex): string {
  return [
    '---',
    '',
    `*Generated by KnowledgeIndexer v${index.version} on ${index.updatedAt.split('T')[0]}*`,
    '',
  ].join('\n');
}
