import { join, resolve } from 'node:path';
import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { loadConfig } from '../config/loader.js';
import { createJsonStore } from '../storage/json-store.js';
import { createRateLimiter } from '../summarizer/rate-limiter.js';
import { createGitConnector } from '../connectors/git/git-connector.js';
import { runPipeline } from '../indexer/indexing-pipeline.js';
import { exportMarkdown } from '../output/markdown-generator.js';
import { exportToYaml } from '../storage/yaml-exporter.js';
import { pickClient } from '../summarizer/llm-factory.js';
import type { Connector } from '../types/connector.js';
import type { SourceType } from '../types/source.js';
import type { KnowledgeIndex } from '../types/index-schema.js';

// Backpressure cap for outbound LLM calls. The configured provider (Anthropic
// or OpenAI-compatible) typically enforces its own quota; this just smooths
// bursts.
const REQUESTS_PER_MINUTE = 60;

function getConnector(type: SourceType): Connector {
  switch (type) {
    case 'git':
      return createGitConnector();
    default:
      throw new Error(`Unsupported source type: ${type}`);
  }
}

function text(content: string): { content: Array<{ type: 'text'; text: string }> } {
  return { content: [{ type: 'text', text: content }] };
}

function formatList(indices: readonly KnowledgeIndex[]): string {
  if (indices.length === 0) return 'No indexed sources.';
  return indices
    .map((i) =>
      [
        `${i.source.id}  ${i.source.name}`,
        `  type: ${i.source.metadata.type}`,
        `  url: ${i.source.metadata.url}`,
        `  lastIndexedAt: ${i.source.metadata.lastIndexedAt}`,
        `  features: ${i.features.length}, codeElements: ${i.functionUnits.length}`,
      ].join('\n'),
    )
    .join('\n\n');
}

function formatShow(index: KnowledgeIndex): string {
  const { source } = index;
  const header = [
    `Source: ${source.name} (${source.id})`,
    `Summary: ${source.summary}`,
    `Type: ${source.metadata.type}`,
    `URL: ${source.metadata.url}`,
    `Version: ${source.metadata.version ?? 'N/A'}`,
    `Last Indexed: ${source.metadata.lastIndexedAt}`,
  ].join('\n');

  const features = index.features
    .map((f) => {
      const path = f.metadata.path ? `\n    path: ${f.metadata.path}` : '';
      return `  ${f.name} (${f.functionUnits.length} elements)\n    ${f.summary}${path}`;
    })
    .join('\n\n');

  return `${header}\n\nFeatures (${index.features.length}):\n\n${features}\n\nTotal: ${index.features.length} features, ${index.functionUnits.length} code elements`;
}

function formatMatches(index: KnowledgeIndex, term: string): string | null {
  const lower = term.toLowerCase();
  const features = index.features.filter(
    (f) =>
      f.name.toLowerCase().includes(lower) ||
      f.summary.toLowerCase().includes(lower),
  );
  const units = index.functionUnits.filter(
    (u) =>
      u.name.toLowerCase().includes(lower) ||
      u.description.toLowerCase().includes(lower),
  );

  if (features.length === 0 && units.length === 0) return null;

  const featureLines = features.map((f) => `  [Feature] ${f.name}\n    ${f.summary}`);
  const unitLines = units.map((u) => {
    const file = u.metadata.filePath ?? '';
    const line = u.metadata.lineStart ? `:${u.metadata.lineStart}` : '';
    const loc = file ? `\n    ${file}${line}` : '';
    return `  [${u.metadata.kind}] ${u.name}\n    ${u.description}${loc}`;
  });

  return `--- ${index.source.name} ---\n${[...featureLines, ...unitLines].join('\n')}`;
}

export function registerTools(mcp: McpServer): void {
  mcp.registerTool(
    'index_source',
    {
      description:
        'Index a knowledge source (currently: a local git repository). Summaries are generated by the server using its configured LLM (Anthropic, or any OpenAI-compatible endpoint including self-hosted models).',
      inputSchema: {
        target: z.string().describe('Absolute or relative path to the source'),
        type: z
          .enum(['git', 'confluence', 'jira', 'custom'])
          .default('git')
          .describe('Source type'),
        include: z.array(z.string()).optional().describe('Glob patterns to include'),
        exclude: z.array(z.string()).optional().describe('Glob patterns to exclude'),
        force: z.boolean().default(false).describe('Re-index even if no changes'),
        dryRun: z
          .boolean()
          .default(false)
          .describe('Scan only; no LLM calls, no summaries'),
      },
    },
    async ({ target, type, include, exclude, force, dryRun }) => {
      const config = loadConfig();
      const connector = getConnector(type);
      const store = createJsonStore(config.dataDir);
      const client = pickClient(config.llm);
      const rateLimiter = createRateLimiter(REQUESTS_PER_MINUTE);

      const result = await runPipeline(resolve(target), {
        connector,
        store,
        client,
        rateLimiter,
        maxConcurrent: config.maxConcurrentSummarizations,
        scanOptions: { include, exclude },
        force,
        dryRun,
      });

      if (result.stats.skipped) {
        return text(`No changes detected for ${target}. Pass force=true to re-index.`);
      }

      return text(
        `Indexed ${result.index.source.name}\n` +
          `  id: ${result.index.source.id}\n` +
          `  features: ${result.stats.features}, codeElements: ${result.stats.functionUnits}`,
      );
    },
  );

  mcp.registerTool(
    'list_sources',
    {
      description: 'List all indexed knowledge sources.',
      inputSchema: {},
    },
    async () => {
      const config = loadConfig();
      const store = createJsonStore(config.dataDir);
      const ids = await store.list();
      const indices = (
        await Promise.all(ids.map((id) => store.load(id)))
      ).filter((i): i is KnowledgeIndex => i !== null);
      return text(formatList(indices));
    },
  );

  mcp.registerTool(
    'show_source',
    {
      description: 'Show full details (summary, features, code elements) for an indexed source.',
      inputSchema: {
        sourceId: z.string().describe('Source ID returned by list_sources or index_source'),
      },
    },
    async ({ sourceId }) => {
      const config = loadConfig();
      const store = createJsonStore(config.dataDir);
      const index = await store.load(sourceId);
      if (!index) throw new Error(`Source not found: ${sourceId}`);
      return text(formatShow(index));
    },
  );

  mcp.registerTool(
    'query',
    {
      description:
        'Case-insensitive search across feature and code-element names/summaries. Limit to one source via sourceId.',
      inputSchema: {
        term: z.string().min(1).describe('Search term'),
        sourceId: z.string().optional().describe('Limit search to this source'),
      },
    },
    async ({ term, sourceId }) => {
      const config = loadConfig();
      const store = createJsonStore(config.dataDir);
      const ids = sourceId ? [sourceId] : await store.list();

      if (ids.length === 0) return text('No indexed sources to search.');

      const blocks: string[] = [];
      for (const id of ids) {
        const index = await store.load(id);
        if (!index) continue;
        const block = formatMatches(index, term);
        if (block) blocks.push(block);
      }

      if (blocks.length === 0) return text(`No results found for "${term}".`);
      return text(blocks.join('\n\n'));
    },
  );

  mcp.registerTool(
    'export_source',
    {
      description:
        'Re-emit indexed sources as KNOWLEDGE.md and/or YAML without re-running the pipeline. Omit sourceId to export all.',
      inputSchema: {
        sourceId: z.string().optional(),
        format: z.enum(['md', 'yaml', 'both']).default('md'),
        output: z.string().default('.').describe('Output directory'),
      },
    },
    async ({ sourceId, format, output }) => {
      const config = loadConfig();
      const store = createJsonStore(config.dataDir);
      const ids = sourceId ? [sourceId] : await store.list();

      if (ids.length === 0) return text('No indexed sources to export.');

      const written: string[] = [];
      for (const id of ids) {
        const index = await store.load(id);
        if (!index) continue;
        const basePath = join(output, index.source.name);

        if (format === 'md' || format === 'both') {
          const mdPath = `${basePath}.KNOWLEDGE.md`;
          await exportMarkdown(index, mdPath);
          written.push(mdPath);
        }
        if (format === 'yaml' || format === 'both') {
          const yamlPath = `${basePath}.knowledge.yaml`;
          await exportToYaml(index, yamlPath);
          written.push(yamlPath);
        }
      }

      return text(`Exported:\n${written.map((p) => `  ${p}`).join('\n')}`);
    },
  );
}
